export const serviceSeeds = [
  {
    id: "SRV-001",
    name: "Regular Cleaning",
    category: "residential",
    categoryLabel: "Residential",
    description: "Limpeza residencial recorrente padrão",
    typicalFrequency: "Weekly / Fortnightly",
    defaultDurationHours: 2,
    checklistTemplateKey: "Residential_Standard",
    inventoryRequired: false,
    photosRequired: false,
    inventoryTemplateKey: null,
    active: true,
  },
  {
    id: "SRV-002",
    name: "Deep Cleaning",
    category: "residential",
    categoryLabel: "Residential",
    description: "Limpeza residencial profunda",
    typicalFrequency: "One-off / Seasonal",
    defaultDurationHours: 5,
    checklistTemplateKey: "Deep_Cleaning",
    inventoryRequired: false,
    photosRequired: true,
    inventoryTemplateKey: null,
    active: true,
  },
  {
    id: "SRV-003",
    name: "End of Tenancy",
    category: "residential",
    categoryLabel: "Residential",
    description: "Limpeza para fim de contrato de aluguel",
    typicalFrequency: "Move-out",
    defaultDurationHours: 6,
    checklistTemplateKey: "End_Tenancy",
    inventoryRequired: false,
    photosRequired: true,
    inventoryTemplateKey: null,
    active: true,
  },
  {
    id: "SRV-004",
    name: "After Builders",
    category: "specialized",
    categoryLabel: "Specialized",
    description: "Limpeza pós-obra",
    typicalFrequency: "After renovation",
    defaultDurationHours: 6,
    checklistTemplateKey: "Post_Construction",
    inventoryRequired: false,
    photosRequired: true,
    inventoryTemplateKey: null,
    active: true,
  },
  {
    id: "SRV-005",
    name: "Office Cleaning",
    category: "commercial",
    categoryLabel: "Commercial",
    description: "Limpeza de escritório",
    typicalFrequency: "Weekly / Daily",
    defaultDurationHours: 2.5,
    checklistTemplateKey: "Office_Cleaning",
    inventoryRequired: false,
    photosRequired: false,
    inventoryTemplateKey: null,
    active: true,
  },
  {
    id: "SRV-006",
    name: "Carpet Cleaning",
    category: "specialized",
    categoryLabel: "Specialized",
    description: "Limpeza especializada de carpetes",
    typicalFrequency: "As needed",
    defaultDurationHours: 2,
    checklistTemplateKey: "Carpet_Cleaning",
    inventoryRequired: false,
    photosRequired: false,
    inventoryTemplateKey: null,
    active: true,
  },
  {
    id: "SRV-007",
    name: "Window Cleaning",
    category: "specialized",
    categoryLabel: "Specialized",
    description: "Limpeza de janelas",
    typicalFrequency: "Monthly / As needed",
    defaultDurationHours: 1.5,
    checklistTemplateKey: "Window_Cleaning",
    inventoryRequired: false,
    photosRequired: false,
    inventoryTemplateKey: null,
    active: true,
  },
  {
    id: "SRV-008",
    name: "Holiday Let Cleaning",
    category: "airbnb",
    categoryLabel: "Airbnb",
    description: "Limpeza turnover com troca de roupa de cama",
    typicalFrequency: "Entre hóspedes",
    defaultDurationHours: 1.5,
    checklistTemplateKey: "Airbnb_Turnover",
    inventoryRequired: true,
    photosRequired: true,
    inventoryTemplateKey: "INV_AIRBNB_STANDARD",
    active: true,
  },
  {
    id: "SRV-009",
    name: "Laundry Service",
    category: "airbnb",
    categoryLabel: "Airbnb",
    description: "Serviço de lavandaria ligado a estadias",
    typicalFrequency: "Entre hóspedes",
    defaultDurationHours: 1.5,
    checklistTemplateKey: "Laundry",
    inventoryRequired: false,
    photosRequired: false,
    inventoryTemplateKey: null,
    active: true,
  },
  {
    id: "SRV-010",
    name: "Restock Service",
    category: "airbnb",
    categoryLabel: "Airbnb",
    description: "Reposição básica de itens para estadias",
    typicalFrequency: "Entre hóspedes",
    defaultDurationHours: 0.5,
    checklistTemplateKey: "Restock",
    inventoryRequired: true,
    photosRequired: false,
    inventoryTemplateKey: "INV_AIRBNB_STANDARD",
    active: true,
  },
  {
    id: "SRV-011",
    name: "Oven Cleaning",
    category: "specialized",
    categoryLabel: "Specialized",
    description: "Limpeza especializada de forno",
    typicalFrequency: "As needed",
    defaultDurationHours: 1,
    checklistTemplateKey: "Oven_Cleaning",
    inventoryRequired: false,
    photosRequired: true,
    inventoryTemplateKey: null,
    active: true,
  },
] as const;
